"""Safe, disposable image normalization for post-capture analysis."""

from __future__ import annotations

import struct
import warnings
from dataclasses import dataclass
from io import BytesIO
from typing import Final, Protocol, runtime_checkable


SUPPORTED_INPUT_MIME_TYPES: Final[frozenset[str]] = frozenset(
    {"image/jpeg", "image/png", "image/webp"}
)
CANONICAL_ANALYSIS_MIME_TYPE: Final[str] = "image/png"
MAX_ANALYSIS_PIXELS: Final[int] = 50_000_000
MAX_ANALYSIS_BYTES: Final[int] = 10 * 1024 * 1024
_FORMAT_TO_MIME: Final[dict[str, str]] = {
    "JPEG": "image/jpeg",
    "PNG": "image/png",
    "WEBP": "image/webp",
}


class ImageNormalizationError(ValueError):
    code: Final[str] = "NORMALIZATION_FAILED"


class InvalidImageInputError(ImageNormalizationError):
    code: Final[str] = "INVALID_INPUT"


class PillowUnavailableError(ImageNormalizationError):
    code: Final[str] = "PILLOW_UNAVAILABLE"


class UnsupportedImageFormatError(ImageNormalizationError):
    code: Final[str] = "UNSUPPORTED_FORMAT"


class ImageMimeMismatchError(UnsupportedImageFormatError):
    code: Final[str] = "MIME_MISMATCH"


class ImageDecodeError(ImageNormalizationError):
    code: Final[str] = "DECODE_FAILED"


class ImageConversionError(ImageNormalizationError):
    code: Final[str] = "CONVERSION_FAILED"


@dataclass(frozen=True, slots=True)
class NormalizedAnalysisImage:
    """Canonical sRGB PNG copy; the original capture is never retained here."""

    data: bytes
    width: int
    height: int
    mime_type: str = CANONICAL_ANALYSIS_MIME_TYPE
    is_srgb: bool = True

    def __post_init__(self) -> None:
        if not isinstance(self.data, bytes) or not self.data:
            raise InvalidImageInputError("normalized image data must be non-empty bytes")
        if not isinstance(self.width, int) or self.width <= 0:
            raise ImageConversionError("normalized image width must be positive")
        if not isinstance(self.height, int) or self.height <= 0:
            raise ImageConversionError("normalized image height must be positive")
        if self.mime_type != CANONICAL_ANALYSIS_MIME_TYPE:
            raise ImageConversionError("normalized analysis images must be PNG")
        if self.is_srgb is not True:
            raise ImageConversionError("normalized analysis images must be sRGB")


@runtime_checkable
class ImageNormalizer(Protocol):
    def normalize(self, data: bytes, mime_type: str) -> NormalizedAnalysisImage:
        """Return a disposable analysis copy without retaining the input."""


def _declared_mime(mime_type: str | None) -> str | None:
    if mime_type is None:
        return None
    if not isinstance(mime_type, str):
        raise UnsupportedImageFormatError("image MIME type must be a string")
    normalized = mime_type.split(";", 1)[0].strip().lower()
    if normalized not in SUPPORTED_INPUT_MIME_TYPES:
        raise UnsupportedImageFormatError("unsupported image MIME type")
    return normalized


def _canonical_srgb_profile(image_cms: object) -> tuple[bytes, object]:
    generated = image_cms.ImageCmsProfile(image_cms.createProfile("sRGB"))  # type: ignore[attr-defined]
    generated_bytes = generated.tobytes()
    if len(generated_bytes) < 128 or generated_bytes[36:40] != b"acsp":
        raise ImageConversionError("Pillow did not create a valid sRGB profile")
    canonical = bytearray(generated_bytes)
    # These fields are volatile in profiles generated by different LittleCMS
    # builds; fixing them makes fixture output deterministic across machines.
    canonical[24:36] = struct.pack(">6H", 2000, 1, 1, 0, 0, 0)
    canonical[84:100] = bytes(16)
    profile_bytes = bytes(canonical)
    return profile_bytes, image_cms.ImageCmsProfile(BytesIO(profile_bytes))  # type: ignore[attr-defined]


def normalize_upload_for_analysis(
    original_bytes: bytes,
    mime_type: str | None = None,
) -> NormalizedAnalysisImage:
    """Decode, orient, convert to sRGB, and encode an analysis-only PNG."""

    if not isinstance(original_bytes, bytes) or not original_bytes:
        raise InvalidImageInputError("image data must be non-empty bytes")
    if len(original_bytes) > MAX_ANALYSIS_BYTES:
        raise InvalidImageInputError("image exceeds the upload size limit")
    declared_mime = _declared_mime(mime_type)

    try:
        from PIL import Image, ImageCms, ImageOps, UnidentifiedImageError
    except (ImportError, ModuleNotFoundError) as error:
        raise PillowUnavailableError("Pillow is required to normalize images") from error

    decoded_copy = None
    oriented = None
    color_source = None
    rgb = None
    alpha = None
    with warnings.catch_warnings():
        warnings.simplefilter("error", Image.DecompressionBombWarning)
        try:
            with Image.open(BytesIO(original_bytes)) as decoded:
                actual_mime = _FORMAT_TO_MIME.get(decoded.format or "")
                if actual_mime is None:
                    raise UnsupportedImageFormatError("unsupported decoded image format")
                if declared_mime is not None and declared_mime != actual_mime:
                    raise ImageMimeMismatchError("declared MIME type does not match decoded image")
                pixel_count = decoded.width * decoded.height
                if pixel_count <= 0 or pixel_count > MAX_ANALYSIS_PIXELS:
                    raise ImageDecodeError("image dimensions exceed the safe decode limit")
                decoded.load()
                decoded_copy = decoded.copy()
        except ImageNormalizationError:
            raise
        except (Image.DecompressionBombWarning, Image.DecompressionBombError) as error:
            raise ImageDecodeError("image dimensions exceed the safe decode limit") from error
        except (UnidentifiedImageError, OSError, ValueError, SyntaxError) as error:
            raise ImageDecodeError("image bytes could not be decoded") from error

    try:
        oriented = ImageOps.exif_transpose(decoded_copy)
        alpha = oriented.getchannel("A") if "A" in oriented.getbands() else None
        # Convert palette, grayscale, CMYK, and RGB inputs through the same
        # RGB path before optional ICC conversion.
        color_source = oriented.convert("RGB")
        input_icc = decoded_copy.info.get("icc_profile")
        profile_bytes, srgb_profile = _canonical_srgb_profile(ImageCms)
        if input_icc:
            source_profile = ImageCms.ImageCmsProfile(BytesIO(input_icc))
            rgb = ImageCms.profileToProfile(
                color_source,
                source_profile,
                srgb_profile,
                renderingIntent=ImageCms.Intent.PERCEPTUAL,
                outputMode="RGB",
            )
        else:
            rgb = color_source.copy()
        if alpha is not None:
            rgb.putalpha(alpha)
        rgb.info.clear()
        output = BytesIO()
        rgb.save(
            output,
            format="PNG",
            optimize=False,
            compress_level=9,
            icc_profile=profile_bytes,
        )
        data = output.getvalue()
        if not data:
            raise ImageConversionError("normalization produced no image data")
        return NormalizedAnalysisImage(data=data, width=rgb.width, height=rgb.height)
    except ImageNormalizationError:
        raise
    except Exception as error:
        raise ImageConversionError("image could not be converted to sRGB") from error
    finally:
        for image in (alpha, rgb, color_source, oriented, decoded_copy):
            if image is not None:
                try:
                    image.close()
                except Exception:
                    pass


normalize_image_for_analysis = normalize_upload_for_analysis
normalize_image = normalize_upload_for_analysis


class PillowImageNormalizer:
    def normalize(self, data: bytes, mime_type: str) -> NormalizedAnalysisImage:
        return normalize_upload_for_analysis(data, mime_type)


# Measurement has its own HTTP/provider boundary, but it must use the same
# disposable canonical copy as post-capture analysis.  Keeping a named seam
# makes that separation explicit and lets tests inject a measurement-only
# normalizer without touching ShotAssessor.
def normalize_measurement_image(
    original_bytes: bytes,
    mime_type: str | None = None,
) -> NormalizedAnalysisImage:
    """Create the disposable sRGB PNG sent to the measurement provider."""

    return normalize_upload_for_analysis(original_bytes, mime_type)


normalize_measurement_image_for_analysis = normalize_measurement_image
normalize_upload_for_measurement = normalize_measurement_image


class MeasurementImageNormalizer:
    """Named normalizer seam for the dedicated measurement route."""

    def normalize(self, data: bytes, mime_type: str) -> NormalizedAnalysisImage:
        return normalize_measurement_image(data, mime_type)


AnalysisImage = NormalizedAnalysisImage


__all__ = [
    "AnalysisImage",
    "CANONICAL_ANALYSIS_MIME_TYPE",
    "ImageConversionError",
    "ImageDecodeError",
    "ImageMimeMismatchError",
    "ImageNormalizationError",
    "ImageNormalizer",
    "InvalidImageInputError",
    "MAX_ANALYSIS_BYTES",
    "MAX_ANALYSIS_PIXELS",
    "MeasurementImageNormalizer",
    "NormalizedAnalysisImage",
    "PillowImageNormalizer",
    "PillowUnavailableError",
    "SUPPORTED_INPUT_MIME_TYPES",
    "UnsupportedImageFormatError",
    "normalize_image",
    "normalize_image_for_analysis",
    "normalize_measurement_image",
    "normalize_measurement_image_for_analysis",
    "normalize_upload_for_measurement",
    "normalize_upload_for_analysis",
]
