import { sql } from 'drizzle-orm';
import { integer, primaryKey, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const createdAt = () => text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`);
const updatedAt = () => text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`);
const json = (name: string) => text(name, { mode: 'json' });

export const users = sqliteTable('users', {
  id: text('id').primaryKey(), displayName: text('display_name').notNull(), avatar: text('avatar').notNull().default(''), bio: text('bio').notNull().default(''),
  status: text('status').notNull().default('ACTIVE'), identityVerificationStatus: text('identity_verification_status').notNull().default('UNVERIFIED'), phoneVerified: integer('phone_verified', { mode: 'boolean' }).notNull().default(false),
  ratingAverage: real('rating_average').notNull().default(0), ratingCount: integer('rating_count').notNull().default(0), sellerLevel: integer('seller_level').notNull().default(1), salesBalance: integer('sales_balance').notNull().default(0), points: integer('points').notNull().default(0), createdAt: createdAt(),
});

export const addresses = sqliteTable('addresses', { id: text('id').primaryKey(), userId: text('user_id').notNull(), label: text('label').notNull(), postalCode: text('postal_code').notNull(), prefecture: text('prefecture').notNull(), city: text('city').notNull(), line1: text('line1').notNull(), isDefault: integer('is_default', { mode: 'boolean' }).notNull().default(false), createdAt: createdAt() });
export const paymentMethods = sqliteTable('payment_methods', { id: text('id').primaryKey(), userId: text('user_id').notNull(), type: text('type').notNull(), label: text('label').notNull(), isDefault: integer('is_default', { mode: 'boolean' }).notNull().default(false), createdAt: createdAt() });
export const userPreferences = sqliteTable('user_preferences', { userId: text('user_id').primaryKey(), notificationEnabled: integer('notification_enabled', { mode: 'boolean' }).notNull().default(true), language: text('language').notNull().default('ja') });

export const items = sqliteTable('items', { id: text('id').primaryKey(), title: text('title').notNull(), description: text('description').notNull().default(''), condition: text('condition').notNull(), defectDescription: text('defect_description').notNull().default(''), createdAt: createdAt() });
export const categories = sqliteTable('categories', { id: text('id').primaryKey(), name: text('name').notNull(), parentId: text('parent_id') });
export const categoryAttributeDefinitions = sqliteTable('category_attribute_definitions', { id: text('id').primaryKey(), categoryId: text('category_id').notNull(), key: text('key').notNull(), label: text('label').notNull(), required: integer('required', { mode: 'boolean' }).notNull().default(false), options: json('options') });
export const listings = sqliteTable('listings', {
  id: text('id').primaryKey(), itemId: text('item_id').notNull(), sellerId: text('seller_id').notNull(), categoryId: text('category_id').notNull(), brandId: text('brand_id'), attributes: json('attributes').notNull().default({}), price: integer('price').notNull(), saleType: text('sale_type').notNull().default('FIXED_PRICE'),
  shippingPayer: text('shipping_payer').notNull(), shippingMethod: text('shipping_method').notNull(), shippingOrigin: text('shipping_origin').notNull(), shippingDays: integer('shipping_days').notNull(), packageSize: text('package_size').notNull(), isAnonymous: integer('is_anonymous', { mode: 'boolean' }).notNull().default(true), status: text('status').notNull(), availability: text('availability').notNull().default('AVAILABLE'), quantity: integer('quantity').notNull().default(1), version: integer('version').notNull().default(1), viewsCount: integer('views_count').notNull().default(0), searchCount: integer('search_count').notNull().default(0), likesCount: integer('likes_count').notNull().default(0), createdAt: createdAt(), publishedAt: text('published_at'), updatedAt: updatedAt(),
});
export const listingImages = sqliteTable('listing_images', { id: text('id').primaryKey(), listingId: text('listing_id').notNull(), url: text('url').notNull(), sortOrder: integer('sort_order').notNull(), width: integer('width'), height: integer('height') });
export const listingAttributes = sqliteTable('listing_attributes', { listingId: text('listing_id').notNull(), definitionId: text('definition_id').notNull(), value: text('value').notNull(), createdAt: createdAt() }, (table) => ({ pk: primaryKey({ columns: [table.listingId, table.definitionId] }) }));

export const listingComments = sqliteTable('comments', { id: text('id').primaryKey(), listingId: text('listing_id').notNull(), authorId: text('author_id').notNull(), body: text('body').notNull(), status: text('status').notNull().default('ACTIVE'), createdAt: createdAt() });
export const likes = sqliteTable('likes', { userId: text('user_id').notNull(), listingId: text('listing_id').notNull(), createdAt: createdAt() }, (table) => ({ pk: primaryKey({ columns: [table.userId, table.listingId] }) }));
export const savedItems = sqliteTable('saved_items', { userId: text('user_id').notNull(), listingId: text('listing_id').notNull(), createdAt: createdAt() }, (table) => ({ pk: primaryKey({ columns: [table.userId, table.listingId] }) }));
export const collections = sqliteTable('collections', { id: text('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), createdAt: createdAt() });
export const collectionItems = sqliteTable('collection_items', { collectionId: text('collection_id').notNull(), listingId: text('listing_id').notNull(), createdAt: createdAt() }, (table) => ({ pk: primaryKey({ columns: [table.collectionId, table.listingId] }) }));
export const follows = sqliteTable('follows', { followerId: text('follower_id').notNull(), followedUserId: text('followed_user_id').notNull(), createdAt: createdAt() }, (table) => ({ pk: primaryKey({ columns: [table.followerId, table.followedUserId] }) }));
export const blocks = sqliteTable('blocks', { blockerId: text('blocker_id').notNull(), blockedId: text('blocked_id').notNull(), createdAt: createdAt() }, (table) => ({ pk: primaryKey({ columns: [table.blockerId, table.blockedId] }) }));
export const savedSearches = sqliteTable('saved_searches', { id: text('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), query: text('query').notNull(), filters: json('filters').notNull().default({}), notificationEnabled: integer('notification_enabled', { mode: 'boolean' }).notNull().default(true), notificationFrequency: text('notification_frequency').notNull().default('INSTANT'), createdAt: createdAt() });

export const checkoutSessions = sqliteTable('checkout_sessions', { id: text('id').primaryKey(), buyerId: text('buyer_id').notNull(), listingId: text('listing_id').notNull(), paymentMethodId: text('payment_method_id').notNull(), shippingAddressId: text('shipping_address_id').notNull(), pointsUsed: integer('points_used').notNull().default(0), itemPrice: integer('item_price').notNull(), paymentFee: integer('payment_fee').notNull().default(0), shippingCharge: integer('shipping_charge').notNull().default(0), discount: integer('discount').notNull().default(0), total: integer('total').notNull(), listingVersion: integer('listing_version').notNull(), status: text('status').notNull().default('OPEN'), expiresAt: text('expires_at').notNull(), createdAt: createdAt() });
export const transactions = sqliteTable('transactions', { id: text('id').primaryKey(), listingId: text('listing_id').notNull(), sellerId: text('seller_id').notNull(), buyerId: text('buyer_id').notNull(), transactionStatus: text('transaction_status').notNull(), paymentStatus: text('payment_status').notNull(), fulfillmentStatus: text('fulfillment_status').notNull(), buyerRatingStatus: text('buyer_rating_status').notNull(), sellerRatingStatus: text('seller_rating_status').notNull(), disputeStatus: text('dispute_status').notNull(), checkoutId: text('checkout_id').notNull(), paymentId: text('payment_id').notNull(), shipmentId: text('shipment_id').notNull(), shippingAddressSnapshot: json('shipping_address_snapshot').notNull(), expectedListingVersion: integer('expected_listing_version').notNull(), itemPrice: integer('item_price').notNull(), platformFee: integer('platform_fee').notNull(), shippingFee: integer('shipping_fee').notNull(), total: integer('total').notNull(), shippingDeadline: text('shipping_deadline').notNull(), completedAt: text('completed_at'), canceledAt: text('canceled_at'), createdAt: createdAt() });
export const payments = sqliteTable('payments', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), method: text('method').notNull(), amount: integer('amount').notNull(), fee: integer('fee').notNull().default(0), pointsUsed: integer('points_used').notNull().default(0), balanceUsed: integer('balance_used').notNull().default(0), status: text('status').notNull(), paidAt: text('paid_at'), createdAt: createdAt() });
export const shipments = sqliteTable('shipments', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), carrier: text('carrier').notNull(), service: text('service').notNull(), trackingNumber: text('tracking_number'), packageSize: text('package_size').notNull(), shippingFee: integer('shipping_fee').notNull(), senderPays: integer('sender_pays', { mode: 'boolean' }).notNull(), anonymous: integer('anonymous', { mode: 'boolean' }).notNull(), origin: text('origin').notNull(), destination: json('destination').notNull(), status: text('status').notNull(), shippedAt: text('shipped_at'), deliveredAt: text('delivered_at') });
export const transactionMessages = sqliteTable('transaction_messages', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), senderId: text('sender_id').notNull(), body: text('body').notNull(), attachments: json('attachments').notNull().default([]), createdAt: createdAt() });
export const ratings = sqliteTable('ratings', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), fromUserId: text('from_user_id').notNull(), toUserId: text('to_user_id').notNull(), rating: integer('rating').notNull(), comment: text('comment').notNull().default(''), createdAt: createdAt() });
export const sellerProceeds = sqliteTable('seller_proceeds', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), sellerId: text('seller_id').notNull(), gross: integer('gross').notNull(), platformFee: integer('platform_fee').notNull(), shippingFee: integer('shipping_fee').notNull(), adjustments: integer('adjustments').notNull().default(0), net: integer('net').notNull(), status: text('status').notNull(), createdAt: createdAt() });

export const cancellations = sqliteTable('cancellation_requests', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), requestedBy: text('requested_by').notNull(), reason: text('reason').notNull(), reasonDetail: text('reason_detail').notNull().default(''), returnRequired: integer('return_required', { mode: 'boolean' }).notNull().default(false), status: text('status').notNull(), createdAt: createdAt(), respondedAt: text('responded_at') });
export const returns = sqliteTable('returns', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), reason: text('reason').notNull(), shippingMethod: text('shipping_method'), trackingNumber: text('tracking_number'), status: text('status').notNull() });
export const refunds = sqliteTable('refunds', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), paymentId: text('payment_id').notNull(), amount: integer('amount').notNull(), type: text('type').notNull(), reason: text('reason').notNull(), status: text('status').notNull() });
export const disputes = sqliteTable('disputes', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), openedBy: text('opened_by').notNull(), category: text('category').notNull(), description: text('description').notNull(), attachments: json('attachments').notNull().default([]), status: text('status').notNull() });
export const priceRequests = sqliteTable('price_requests', { id: text('id').primaryKey(), listingId: text('listing_id').notNull(), buyerId: text('buyer_id').notNull(), requestedPrice: integer('requested_price').notNull(), status: text('status').notNull(), expiresAt: text('expires_at').notNull() });
export const bundleRequests = sqliteTable('bundle_requests', { id: text('id').primaryKey(), buyerId: text('buyer_id').notNull(), sellerId: text('seller_id').notNull(), listingIds: json('listing_ids').notNull(), requestedTotalPrice: integer('requested_total_price').notNull(), status: text('status').notNull(), expiresAt: text('expires_at').notNull(), bundleListingId: text('bundle_listing_id') });

export const auctions = sqliteTable('auctions', { id: text('id').primaryKey(), listingId: text('listing_id').notNull(), startPrice: integer('start_price').notNull(), startsAt: text('starts_at').notNull(), endsAt: text('ends_at').notNull(), status: text('status').notNull(), highestBidId: text('highest_bid_id'), winnerId: text('winner_id'), purchaseDeadline: text('purchase_deadline') });
export const bids = sqliteTable('bids', { id: text('id').primaryKey(), auctionId: text('auction_id').notNull(), bidderId: text('bidder_id').notNull(), amount: integer('amount').notNull(), createdAt: createdAt() });
export const notifications = sqliteTable('notifications', { id: text('id').primaryKey(), userId: text('user_id').notNull(), type: text('type').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), payload: json('payload').notNull().default({}), isRead: integer('is_read', { mode: 'boolean' }).notNull().default(false), title: text('title').notNull(), content: text('content').notNull(), createdAt: createdAt() });
export const tasks = sqliteTable('tasks', { id: text('id').primaryKey(), userId: text('user_id').notNull(), type: text('type').notNull(), entityId: text('entity_id').notNull(), dueAt: text('due_at'), completedAt: text('completed_at') });
export const reports = sqliteTable('reports', { id: text('id').primaryKey(), reporterId: text('reporter_id').notNull(), targetType: text('target_type').notNull(), targetId: text('target_id').notNull(), category: text('category').notNull(), detail: text('detail').notNull(), createdAt: createdAt() });
export const moderationCases = sqliteTable('moderation_cases', { id: text('id').primaryKey(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), reason: text('reason').notNull(), reportedBy: text('reported_by').notNull(), status: text('status').notNull(), action: text('action') });
export const listingRevisions = sqliteTable('listing_revisions', { listingId: text('listing_id').notNull(), version: integer('version').notNull(), changedFields: json('changed_fields').notNull(), changedAt: text('changed_at').notNull() }, (table) => ({ pk: primaryKey({ columns: [table.listingId, table.version] }) }));
export const transactionEvents = sqliteTable('transaction_events', { id: text('id').primaryKey(), transactionId: text('transaction_id').notNull(), type: text('type').notNull(), actorId: text('actor_id').notNull(), payload: json('payload').notNull().default({}), createdAt: createdAt() });
