/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/generated-env.d.ts` (hash: ccb912acc32122423a64f8446ef562c7)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
