/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品カタログをページ取得する */
        get: {
            parameters: {
                query?: {
                    offset?: components["parameters"]["Offset"];
                    limit?: components["parameters"]["Limit"];
                    q?: string;
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品ページ */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        "X-Catalog-Total"?: number;
                        "X-Catalog-Offset"?: number;
                        "X-Catalog-Limit"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MercariItem"][];
                    };
                };
                /** @description If-None-Matchに一致したため変更なし */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品を1件取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品 */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MercariItem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sandbox状態を取得する */
        get: operations["getSandboxState"];
        /** Sandbox状態を楽観的に更新する */
        put: operations["putSandboxState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sandboxの永続化・実行境界を確認する */
        get: {
            parameters: {
                query?: {
                    sandboxId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SandboxHealth"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandboxコピー上でcommandをシミュレーションする */
        post: operations["previewSandboxAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 未使用・未期限切れのpreviewを確定する */
        post: operations["commitSandboxPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandboxをシナリオ初期状態へ戻す */
        post: operations["resetSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 決定的なseedとシナリオでSandboxを作成する */
        post: operations["seedSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandbox command列を決定的に再生する */
        post: operations["replaySandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 出品写真アシスタントの稼働状態を確認する */
        get: operations["assistantHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/livekit-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 撮影セッション用の短期LiveKit tokenを発行する
         * @description LiveKitの秘密鍵はサーバー内に保持し、ブラウザには撮影用の短期tokenと接続メタデータだけを返します。
         */
        post: operations["issueLiveKitToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze-shot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 撮影後の正面・背面・タグ画像を判定する
         * @description measurement画像はこのAPIへ送信せず、撮影後のShotAssessmentは採寸幾何検証と分離します。
         */
        post: operations["analyzeShot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest-measurement-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 採寸画像から4端点を提案する
         * @description 出力は0〜1の正規化された4端点だけです。cm値、confidence、画面遷移、UI文言は返しません。採寸値の算出、必要に応じた射影補正、端点編集、承認はブラウザ側で行います。
         */
        post: operations["suggestMeasurementPoints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/remove-background": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 正面原本からmask-only PNGを作る
         * @description 正面原本だけを内部のmask providerへ送り、商品RGBを含まないmask-only PNGを返します。rembgはブラウザへ公開しません。
         */
        post: operations["removeBackground"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-background": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 許可されたstyleから商品を含まない背景を生成する
         * @description styleIdを固定promptへ変換し、背景生成サービスへテキストだけを送ります。商品画像、mask、タグ画像、採寸画像はrequestに含めません。
         */
        post: operations["generateBackground"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の出品を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 出品一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MercariItem"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 出品操作（pause/resume/relist） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        operation: "pause" | "resume" | "relist";
                    };
                };
            };
            responses: {
                /** @description 操作結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** 出品を更新する */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path: {
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ListingUpdate"];
                };
            };
            responses: {
                /** @description 更新済み出品 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分のSandboxウォレットと台帳を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ウォレットスナップショット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultWallet"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandbox残高へ入金する */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WalletAmountInput"];
                };
            };
            responses: {
                /** @description 入金後のウォレット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultWallet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 利用可能残高から出金する */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WalletAmountInput"];
                };
            };
            responses: {
                /** @description 出金後のウォレット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultWallet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の表示プロフィールを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 表示プロフィール */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActorProfile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 表示名・自己紹介・画像参照を更新する */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileUpdate"];
                };
            };
            responses: {
                /** @description 更新後プロフィール */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActorProfile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/api/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分のフォロー中・フォロワー一覧を取得する */
        get: {
            parameters: {
                query: {
                    direction: "following" | "followers";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{actorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actorId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザーをフォローする */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー後の関係 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowMutation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        /** ユーザーのフォローを解除する */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー解除後の関係 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowMutation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{actorId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開フォロー数と自分のフォロー状態を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー概要 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssistantHealth: {
            /** @constant */
            status: "ok";
        };
        /**
         * @description 撮影セッション内の固定4slot。measurementは出品画像へ使用しません。
         * @enum {string}
         */
        SessionSlot: "front" | "back" | "tag" | "measurement";
        /**
         * @description 撮影後ShotAssessmentが判定できる3slot。measurementは含みません。
         * @enum {string}
         */
        ShotSlot: "front" | "back" | "tag";
        /** @enum {string} */
        GuidanceCode: "MOVE_CLOSER" | "MOVE_FARTHER" | "CENTER_GARMENT" | "SHOW_FULL_GARMENT" | "WRONG_SIDE" | "MOVE_TO_TAG" | "PLACE_MARKER" | "MARKER_NOT_VISIBLE" | "FLATTEN_GARMENT" | "CAMERA_OVERHEAD" | "HOLD_STEADY" | "READY" | "AGENT_UNAVAILABLE";
        GuidanceEvent: {
            sessionId: string;
            sequence: number;
            shot: components["schemas"]["SessionSlot"];
            code: components["schemas"]["GuidanceCode"];
            message: string;
            confidence: number;
            /** @description Unix epoch milliseconds */
            observedAt: number;
            /** @description Unix epoch milliseconds。observedAtより後である必要があります。 */
            expiresAt: number;
        };
        /** @enum {string} */
        ConnectionState: "connecting" | "connected" | "reconnecting" | "disconnected";
        /** @enum {string} */
        ProviderName: "shot-assessor" | "vision-guidance" | "measurement-line" | "background-generator" | "garment-masker";
        /** @enum {string} */
        ProviderErrorCode: "TIMEOUT" | "UNAVAILABLE" | "INVALID_RESPONSE" | "INVALID_INPUT" | "UNKNOWN";
        ProviderError: {
            provider: components["schemas"]["ProviderName"];
            code: components["schemas"]["ProviderErrorCode"];
            message: string;
            retryable: boolean;
        };
        ProviderErrorResponse: {
            detail: string | components["schemas"]["ProviderError"];
        };
        ValidationErrorResponse: {
            detail: string | {
                [key: string]: unknown;
            }[];
        };
        AssistantValidationErrorResponse: {
            detail: string | components["schemas"]["ProviderError"] | {
                [key: string]: unknown;
            }[];
        };
        LiveKitTokenRequest: {
            sessionId: string;
        };
        LiveKitTokenResponse: {
            /** @description 短期のブラウザ接続token。実値やsecretは公開仕様へ記載しません。 */
            token: string;
            participantIdentity: string;
            roomName: string;
            /** @description Unix epoch seconds */
            expiresAt: number;
            livekitUrl: string;
        };
        /** @enum {string} */
        ShotIssueCode: "TOO_DARK" | "TOO_BRIGHT" | "TOO_BLURRY" | "BLURRY" | "GARMENT_CROPPED" | "TAG_UNREADABLE" | "WRONG_SHOT";
        /** @enum {string} */
        ShotType: "front" | "back" | "tag" | "unknown";
        /** @enum {string} */
        ShotQuality: "ok" | "retry";
        /** @enum {string} */
        NextAction: "RETAKE" | "REQUEST_NEXT" | "COMPLETE";
        ShotAssessment: {
            shotType: components["schemas"]["ShotType"];
            quality: components["schemas"]["ShotQuality"];
            issues: components["schemas"]["ShotIssueCode"][];
            missingShots: components["schemas"]["ShotSlot"][];
            nextAction: components["schemas"]["NextAction"];
        };
        NormalizedPoint: {
            x: number;
            y: number;
        };
        MeasurementEndpoints: {
            lengthStart: components["schemas"]["NormalizedPoint"];
            lengthEnd: components["schemas"]["NormalizedPoint"];
            widthStart: components["schemas"]["NormalizedPoint"];
            widthEnd: components["schemas"]["NormalizedPoint"];
        };
        MeasurementPointSuggestion: {
            lengthStart: components["schemas"]["NormalizedPoint"];
            lengthEnd: components["schemas"]["NormalizedPoint"];
            widthStart: components["schemas"]["NormalizedPoint"];
            widthEnd: components["schemas"]["NormalizedPoint"];
        };
        MeasurementMarker: {
            /**
             * @description 専用マーカー外形1辺のcm値
             * @constant
             */
            knownSideCm: 5;
            corners: components["schemas"]["NormalizedPoint"][];
            pxPerCm: number;
        };
        MeasurementLine: {
            start: components["schemas"]["NormalizedPoint"];
            end: components["schemas"]["NormalizedPoint"];
            valueCm: number;
        };
        /** @enum {string} */
        MeasurementSource: "ai" | "contour" | "user";
        /** @enum {string} */
        MeasurementStatus: "needs_review" | "approved_cv" | "approved_manual";
        /** @enum {string} */
        MeasurementFailureCode: "MARKER_MISSING" | "MARKER_MULTIPLE" | "MARKER_TOO_SMALL" | "MARKER_OCCLUDED" | "GARMENT_OUT_OF_FRAME" | "GARMENT_MARKER_OVERLAP" | "SEGMENTATION_FAILED" | "ENDPOINTS_INVALID";
        MeasurementDraft: {
            /** @description セッション内の一時参照。出品データへ保存しません。 */
            imageId: string;
            marker: components["schemas"]["MeasurementMarker"] | null;
            length: components["schemas"]["MeasurementLine"];
            width: components["schemas"]["MeasurementLine"];
            source: components["schemas"]["MeasurementSource"];
            status: components["schemas"]["MeasurementStatus"];
        };
        ApprovedMeasurement: {
            /** @description セッション内の一時参照。出品データへ保存しません。 */
            imageId: string;
            marker: components["schemas"]["MeasurementMarker"] | null;
            length: components["schemas"]["MeasurementLine"];
            width: components["schemas"]["MeasurementLine"];
            source: components["schemas"]["MeasurementSource"];
            /** @enum {string} */
            status: "approved_cv" | "approved_manual";
        };
        /** @enum {string} */
        BackgroundStyleId: "studio_white" | "warm_neutral" | "light_wood";
        BackgroundGenerationRequest: {
            styleId: components["schemas"]["BackgroundStyleId"];
        };
        ShotAnalysisUpload: {
            requestedShot: components["schemas"]["ShotSlot"];
            /**
             * Format: binary
             * @description JPEG、PNG、またはWebPの撮影画像。最大10MiB。
             */
            file: string;
        };
        MeasurementPointsUpload: {
            /**
             * Format: binary
             * @description JPEG、PNG、またはWebPの採寸画像。最大10MiB。
             */
            file: string;
        };
        FrontImageUpload: {
            /**
             * Format: binary
             * @description front原本。mask生成専用で、生成背景へ転送しません。
             */
            file: string;
        };
        ListingMediaRef: {
            id: string;
            /** @enum {string} */
            source: "camera" | "album" | "legacy";
            /** @enum {string} */
            status: "processing" | "ready" | "error";
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp" | "image/avif" | "image/gif";
            width?: number;
            height?: number;
            byteSize?: number;
            thumbnailRef?: string;
            /** Format: date-time */
            createdAt: string;
            errorCode?: string;
        };
        WalletLedgerEntry: {
            id: string;
            /** @enum {string} */
            type: "DEPOSIT" | "WITHDRAWAL" | "HOLD" | "CAPTURE" | "REFUND" | "SALE" | "FEE";
            amount: number;
            referenceId: string;
            /** Format: date-time */
            at: string;
        };
        WalletSnapshot: {
            actorId: string;
            openingBalance: number;
            availableBalance: number;
            heldBalance: number;
            points: number;
            ledger: components["schemas"]["WalletLedgerEntry"][];
        };
        WalletAmountInput: {
            amount: number;
        };
        ActorProfile: {
            actorId: string;
            displayName: string;
            bio: string;
            avatar: string;
            avatarRef?: string;
            rating: number;
            ratingsCount: number;
            completedSales: number;
            completedPurchases: number;
            isVerified: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        ProfileUpdate: {
            displayName?: string;
            bio?: string;
            avatarRef?: string;
        };
        FollowRelation: {
            id: string;
            followerId: string;
            followeeId: string;
            /** Format: date-time */
            createdAt: string;
        };
        FollowSummary: {
            actorId: string;
            followingCount: number;
            followerCount: number;
            isFollowing: boolean;
        };
        FollowListResult: {
            actorId: string;
            /** @enum {string} */
            direction: "following" | "followers";
            users: components["schemas"]["ActorProfile"][];
            summary: components["schemas"]["FollowSummary"];
        };
        FollowMutationResult: {
            actorId: string;
            targetActorId: string;
            following: boolean;
            relation?: components["schemas"]["FollowRelation"];
            summary: components["schemas"]["FollowSummary"];
        };
        ActionResultFollowList: components["schemas"]["ActionResult"];
        ActionResultFollowSummary: components["schemas"]["ActionResult"];
        ActionResultFollowMutation: components["schemas"]["ActionResult"];
        ActionResultWallet: components["schemas"]["ActionResult"];
        MercariItem: {
            id: string;
            title: string;
            price: number;
            /** @deprecated */
            images?: string[];
            imageRefs?: string[];
            description: string;
            category: string[];
            /** @enum {string} */
            condition: "新品・未使用" | "未使用に近い" | "目立った傷や汚れなし" | "やや傷や汚れあり" | "傷や汚れあり" | "全体的に状態が悪い";
            shippingFee: string;
            shippingMethod: string;
            origin: string;
            shippingDays: string;
            shippingSize?: string;
            isAnonymousShipping?: boolean;
            /** @enum {string} */
            inventoryPolicy?: "SINGLE" | "MULTI";
            inventoryQuantity?: number;
            /** @description 明示承認後に出品下書きへ渡す採寸メタデータだけ。画像・端点・scaleは保存しません。 */
            garmentMeasurements?: {
                lengthCm: number;
                widthCm: number;
                /** @enum {string} */
                source: "approved_cv" | "approved_manual";
            };
        } & (unknown | unknown);
        ListingUpdate: {
            title?: string;
            description?: string;
            price?: number;
            category?: string[];
            /** @enum {string} */
            condition?: "新品・未使用" | "未使用に近い" | "目立った傷や汚れなし" | "やや傷や汚れあり" | "傷や汚れあり" | "全体的に状態が悪い";
            imageRefs?: string[];
        };
        ActionIdentifier: string;
        SandboxState: {
            /** @constant */
            version: "1";
            sandboxId: string;
            scenarioId: string;
            seed: string;
            /** Format: date-time */
            now: string;
            stateVersion: number;
            uiRevision?: number;
            idCounter?: number;
            currentActorId: string;
            actors: {
                [key: string]: unknown;
            }[];
            items: components["schemas"]["MercariItem"][];
            purchaseIntents: {
                [key: string]: unknown;
            }[];
            transactions: {
                [key: string]: unknown;
            }[];
            payments: {
                [key: string]: unknown;
            }[];
            shipments: {
                [key: string]: unknown;
            }[];
            bids: {
                [key: string]: unknown;
            }[];
            reviews: {
                [key: string]: unknown;
            }[];
            returns?: {
                [key: string]: unknown;
            }[];
            messages?: {
                [key: string]: unknown;
            }[];
            supportTickets?: {
                [key: string]: unknown;
            }[];
            profiles?: {
                [key: string]: unknown;
            }[];
            inventoryMovements: {
                [key: string]: unknown;
            }[];
            events: {
                [key: string]: unknown;
            }[];
            notifications: {
                [key: string]: unknown;
            }[];
            wallets: components["schemas"]["WalletSnapshot"][];
            follows: components["schemas"]["FollowRelation"][];
            drafts: {
                [key: string]: Record<string, never>;
            };
            draftOwners: {
                [key: string]: string;
            };
            draftUpdatedAt?: {
                [key: string]: string;
            };
            pendingFailures: string[];
        };
        ActionResult: {
            /** @constant */
            ok: true;
            data: unknown;
            stateVersion: number;
            meta: components["schemas"]["ActionMetadata"];
        } | {
            /** @constant */
            ok: false;
            error: string;
            message?: string;
            stateVersion: number;
            meta: components["schemas"]["ActionMetadata"];
            details?: unknown;
        };
        ActionMetadata: {
            sandboxId: string;
            actorId: components["schemas"]["ActionIdentifier"];
            stateVersion: number;
            operationId: components["schemas"]["ActionIdentifier"];
            commandId?: components["schemas"]["ActionIdentifier"];
            requestId?: components["schemas"]["ActionIdentifier"];
            idempotencyKey?: components["schemas"]["ActionIdentifier"];
            /** @enum {string} */
            mode: "preview" | "commit";
        };
        SandboxPreviewInput: {
            /** @example schemathesis */
            sandboxId?: string;
            /** @enum {string} */
            command: "purchase" | "listing.create" | "wallet.deposit" | "wallet.withdraw";
            payload: Record<string, never>;
            stateVersion?: number;
            expectedStateVersion?: number;
            operationId?: components["schemas"]["ActionIdentifier"];
            commandId?: components["schemas"]["ActionIdentifier"];
            requestId?: components["schemas"]["ActionIdentifier"];
            idempotencyKey?: components["schemas"]["ActionIdentifier"];
        } & (unknown & unknown & unknown);
        SandboxCommitInput: {
            /** @example schemathesis */
            sandboxId?: string;
            previewId: components["schemas"]["ActionIdentifier"];
            stateVersion?: number;
            expectedStateVersion?: number;
            operationId?: components["schemas"]["ActionIdentifier"];
            commandId?: components["schemas"]["ActionIdentifier"];
            requestId?: components["schemas"]["ActionIdentifier"];
            idempotencyKey: components["schemas"]["ActionIdentifier"];
        };
        ActionResultPreview: components["schemas"]["ActionResult"];
        SandboxHealth: {
            /** @constant */
            ok: true;
            ready: boolean;
            sandboxId: string;
            stateVersion: number;
            /** @enum {string} */
            storage: "memory" | "d1";
            capabilities: {
                [key: string]: boolean;
            };
        };
        SandboxSeedInput: {
            /** @example schemathesis */
            id?: string;
            /** @example schemathesis */
            sandboxId?: string;
            /**
             * @default catalog_default
             * @enum {string}
             */
            scenarioId: "catalog_default" | "purchase_happy_path" | "already_sold" | "multi_inventory" | "auction_outbid" | "listing_policy_blocked" | "zero_search_results" | "payment_timeout" | "delivery_delay";
            seed?: string;
            expectedStateVersion?: number;
            idempotencyKey: components["schemas"]["ActionIdentifier"];
        } & unknown;
        SandboxOperationResponse: {
            /** @constant */
            ok: true;
            /** @enum {string} */
            operation: "reset" | "seed";
            sandboxId: string;
            scenarioId?: string;
            seed?: string;
            stateVersion: number;
            state: components["schemas"]["SandboxState"];
        };
        SandboxReplayInput: {
            /** @example schemathesis */
            id?: string;
            /** @example schemathesis */
            sandboxId?: string;
            /**
             * @default catalog_default
             * @enum {string}
             */
            scenarioId: "catalog_default" | "purchase_happy_path" | "already_sold" | "multi_inventory" | "auction_outbid" | "listing_policy_blocked" | "zero_search_results" | "payment_timeout" | "delivery_delay";
            seed?: string;
            baseState?: string;
            /** @description 保存済みSandboxを現在のreplay基準にする場合はtrue。seed/reset直後の状態へ続けて操作する場合に指定する。 */
            fromStored?: boolean;
            expectedStateVersion?: number;
            actions: {
                /** @enum {string} */
                command: "listItem" | "createListingDraft" | "updateListingDraft" | "deleteListingDraft" | "submitListing" | "startPurchase" | "confirmPurchase" | "purchaseItem" | "buyItem" | "placeBid" | "closeAuction" | "shipOrder" | "markDelivered" | "reviewOrder" | "cancelOrder" | "resolveCancellation" | "reviewListing" | "requestReturn" | "confirmReturnReceived" | "sendTransactionMessage" | "createSupportTicket" | "reportTransaction" | "updateListing" | "pauseListing" | "resumeListing" | "relistItem" | "updateProfile" | "getFollowList" | "getFollowSummary" | "followUser" | "unfollowUser" | "depositWallet" | "withdrawWallet" | "switchActor" | "loadScenario" | "resetScenario" | "advanceClock" | "injectFailure" | "importState";
                payload?: {
                    [key: string]: unknown;
                };
                idempotencyKey: components["schemas"]["ActionIdentifier"];
            }[];
        } & unknown;
        SandboxReplayResponse: {
            /** @constant */
            ok: true;
            /** @constant */
            operation: "replay";
            sandboxId: string;
            stateVersion: number;
            results: unknown[];
            trace: unknown[];
            state: components["schemas"]["SandboxState"];
        };
        ErrorResponse: {
            /** @constant */
            ok: false;
            error: string;
            details?: unknown;
        };
    };
    responses: {
        /** @description 入力が不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 認証が必要 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 権限不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description stateVersionまたはETagが競合 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description リソースが存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description D1など依存サービスが利用できない */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 撮影アシスタントのproviderが入力不正、timeout、利用不能、または不正な応答を返した */
        ProviderFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProviderErrorResponse"];
            };
        };
        /** @description 撮影アシスタントの入力形式・画像内容・provider入力が不正 */
        AssistantValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AssistantValidationErrorResponse"];
            };
        };
        /** @description リクエストの形式または値が不正 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
    };
    parameters: {
        ItemId: string;
        Offset: number;
        Limit: number;
        IfMatchStateVersion: number;
        /** @description 任意の相関ID。空白・制御文字を除いてサービス内で検証し、成功時に同じ値を返します（最大200文字）。 */
        RequestId: string;
    };
    requestBodies: never;
    headers: {
        /** @description リソースのバージョン */
        ETag: string;
        /** @description キャッシュを保存しない */
        NoStore: "no-store";
        /** @description MIME sniffingを無効化する */
        NoSniff: "nosniff";
        /** @description リクエストで指定された相関ID（指定時のみ返却） */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSandboxState: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox状態 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxState"];
                };
            };
            /** @description 変更なし */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    putSandboxState: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: {
                "If-Match-State-Version"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxState"];
            };
        };
        responses: {
            /** @description 保存済み状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        id: string;
                        sandboxId: string;
                        stateVersion: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description 状態が8MiBを超えた */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewSandboxAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxPreviewInput"];
            };
        };
        responses: {
            /** @description preview結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResultPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description payloadが8MiBを超えた */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    commitSandboxPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxCommitInput"];
            };
        };
        responses: {
            /** @description commit結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    resetSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxSeedInput"];
            };
        };
        responses: {
            /** @description リセット済みSandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxOperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description JSON bodyのContent-Typeが必要 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    seedSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxSeedInput"];
            };
        };
        responses: {
            /** @description seed済みSandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxOperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description JSON bodyのContent-Typeが必要 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    replaySandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxReplayInput"];
            };
        };
        responses: {
            /** @description 再生後のSandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxReplayResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description JSON bodyのContent-Typeが必要 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description command列の途中で失敗した */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    assistantHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FastAPI assistant serviceが稼働中 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantHealth"];
                };
            };
        };
    };
    issueLiveKitToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveKitTokenRequest"];
            };
        };
        responses: {
            /** @description 撮影セッション用LiveKit接続情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveKitTokenResponse"];
                };
            };
            422: components["responses"]["AssistantValidationError"];
            503: components["responses"]["ProviderFailure"];
        };
    };
    analyzeShot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ShotAnalysisUpload"];
            };
        };
        responses: {
            /** @description 厳格に検証された撮影判定 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotAssessment"];
                };
            };
            413: components["responses"]["ProviderFailure"];
            415: components["responses"]["ProviderFailure"];
            422: components["responses"]["AssistantValidationError"];
            502: components["responses"]["ProviderFailure"];
            503: components["responses"]["ProviderFailure"];
            504: components["responses"]["ProviderFailure"];
        };
    };
    suggestMeasurementPoints: {
        parameters: {
            query?: never;
            header?: {
                /** @description 任意の相関ID。空白・制御文字を除いてサービス内で検証し、成功時に同じ値を返します（最大200文字）。 */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["MeasurementPointsUpload"];
            };
        };
        responses: {
            /** @description 採寸4端点の未承認提案 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    "X-Request-ID": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementPointSuggestion"];
                };
            };
            413: components["responses"]["ProviderFailure"];
            415: components["responses"]["ProviderFailure"];
            422: components["responses"]["AssistantValidationError"];
            502: components["responses"]["ProviderFailure"];
            503: components["responses"]["ProviderFailure"];
            504: components["responses"]["ProviderFailure"];
        };
    };
    removeBackground: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["FrontImageUpload"];
            };
        };
        responses: {
            /** @description 正面原本と同じ寸法のmask-only PNG */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    "X-Content-Type-Options": components["headers"]["NoSniff"];
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            413: components["responses"]["ProviderFailure"];
            415: components["responses"]["ProviderFailure"];
            422: components["responses"]["AssistantValidationError"];
            502: components["responses"]["ProviderFailure"];
            503: components["responses"]["ProviderFailure"];
            504: components["responses"]["ProviderFailure"];
        };
    };
    generateBackground: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackgroundGenerationRequest"];
            };
        };
        responses: {
            /** @description 商品を含まない背景PNG候補 */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            422: components["responses"]["AssistantValidationError"];
            502: components["responses"]["ProviderFailure"];
            503: components["responses"]["ProviderFailure"];
            504: components["responses"]["ProviderFailure"];
        };
    };
}
