/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品カタログをページ取得する */
        get: {
            parameters: {
                query?: {
                    offset?: components["parameters"]["Offset"];
                    limit?: components["parameters"]["Limit"];
                    q?: string;
                    category?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品ページ */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        "X-Catalog-Total"?: number;
                        "X-Catalog-Offset"?: number;
                        "X-Catalog-Limit"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MercariItem"][];
                    };
                };
                /** @description If-None-Matchに一致したため変更なし */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 商品を1件取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 商品 */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MercariItem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sandbox状態を取得する */
        get: operations["getSandboxState"];
        /** Sandbox状態を楽観的に更新する */
        put: operations["putSandboxState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sandboxの永続化・実行境界を確認する */
        get: {
            parameters: {
                query?: {
                    sandboxId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sandbox health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SandboxHealth"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                503: components["responses"]["Unavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandboxコピー上でcommandをシミュレーションする */
        post: operations["previewSandboxAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 未使用・未期限切れのpreviewを確定する */
        post: operations["commitSandboxPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandboxをシナリオ初期状態へ戻す */
        post: operations["resetSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 決定的なseedとシナリオでSandboxを作成する */
        post: operations["seedSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandbox command列を決定的に再生する */
        post: operations["replaySandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の出品を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 出品一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MercariItem"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 出品操作（pause/resume/relist） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        operation: "pause" | "resume" | "relist";
                    };
                };
            };
            responses: {
                /** @description 操作結果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** 出品を更新する */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path: {
                    itemId: components["parameters"]["ItemId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ListingUpdate"];
                };
            };
            responses: {
                /** @description 更新済み出品 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分のSandboxウォレットと台帳を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ウォレットスナップショット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultWallet"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandbox残高へ入金する */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WalletAmountInput"];
                };
            };
            responses: {
                /** @description 入金後のウォレット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultWallet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 利用可能残高から出金する */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WalletAmountInput"];
                };
            };
            responses: {
                /** @description 出金後のウォレット */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultWallet"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の表示プロフィールを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 表示プロフィール */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActorProfile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 表示名・自己紹介・画像参照を更新する */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileUpdate"];
                };
            };
            responses: {
                /** @description 更新後プロフィール */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActorProfile"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/api/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分のフォロー中・フォロワー一覧を取得する */
        get: {
            parameters: {
                query: {
                    direction: "following" | "followers";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー一覧 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{actorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actorId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザーをフォローする */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー後の関係 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowMutation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        /** ユーザーのフォローを解除する */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "If-Match-State-Version"?: components["parameters"]["IfMatchStateVersion"];
                };
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー解除後の関係 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowMutation"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{actorId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公開フォロー数と自分のフォロー状態を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    actorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フォロー概要 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResultFollowSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ListingMediaRef: {
            id: string;
            /** @enum {string} */
            source: "camera" | "album" | "legacy";
            /** @enum {string} */
            status: "processing" | "ready" | "error";
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp" | "image/avif" | "image/gif";
            width?: number;
            height?: number;
            byteSize?: number;
            thumbnailRef?: string;
            /** Format: date-time */
            createdAt: string;
            errorCode?: string;
        };
        WalletLedgerEntry: {
            id: string;
            /** @enum {string} */
            type: "DEPOSIT" | "WITHDRAWAL" | "HOLD" | "CAPTURE" | "REFUND" | "SALE" | "FEE";
            amount: number;
            referenceId: string;
            /** Format: date-time */
            at: string;
        };
        WalletSnapshot: {
            actorId: string;
            openingBalance: number;
            availableBalance: number;
            heldBalance: number;
            points: number;
            ledger: components["schemas"]["WalletLedgerEntry"][];
        };
        WalletAmountInput: {
            amount: number;
        };
        ActorProfile: {
            actorId: string;
            displayName: string;
            bio: string;
            avatar: string;
            avatarRef?: string;
            rating: number;
            ratingsCount: number;
            completedSales: number;
            completedPurchases: number;
            isVerified: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        ProfileUpdate: {
            displayName?: string;
            bio?: string;
            avatarRef?: string;
        };
        FollowRelation: {
            id: string;
            followerId: string;
            followeeId: string;
            /** Format: date-time */
            createdAt: string;
        };
        FollowSummary: {
            actorId: string;
            followingCount: number;
            followerCount: number;
            isFollowing: boolean;
        };
        FollowListResult: {
            actorId: string;
            /** @enum {string} */
            direction: "following" | "followers";
            users: components["schemas"]["ActorProfile"][];
            summary: components["schemas"]["FollowSummary"];
        };
        FollowMutationResult: {
            actorId: string;
            targetActorId: string;
            following: boolean;
            relation?: components["schemas"]["FollowRelation"];
            summary: components["schemas"]["FollowSummary"];
        };
        ActionResultFollowList: components["schemas"]["ActionResult"];
        ActionResultFollowSummary: components["schemas"]["ActionResult"];
        ActionResultFollowMutation: components["schemas"]["ActionResult"];
        ActionResultWallet: components["schemas"]["ActionResult"];
        MercariItem: {
            id: string;
            title: string;
            price: number;
            /** @deprecated */
            images?: string[];
            imageRefs?: string[];
            description: string;
            category: string[];
            /** @enum {string} */
            condition: "新品・未使用" | "未使用に近い" | "目立った傷や汚れなし" | "やや傷や汚れあり" | "傷や汚れあり" | "全体的に状態が悪い";
            shippingFee: string;
            shippingMethod: string;
            origin: string;
            shippingDays: string;
            shippingSize?: string;
            isAnonymousShipping?: boolean;
            /** @enum {string} */
            inventoryPolicy?: "SINGLE" | "MULTI";
            inventoryQuantity?: number;
        } & (unknown | unknown);
        ListingUpdate: {
            title?: string;
            description?: string;
            price?: number;
            category?: string[];
            /** @enum {string} */
            condition?: "新品・未使用" | "未使用に近い" | "目立った傷や汚れなし" | "やや傷や汚れあり" | "傷や汚れあり" | "全体的に状態が悪い";
            imageRefs?: string[];
        };
        SandboxState: {
            /** @constant */
            version: "1";
            sandboxId: string;
            scenarioId: string;
            seed: string;
            /** Format: date-time */
            now: string;
            stateVersion: number;
            currentActorId: string;
            items: components["schemas"]["MercariItem"][];
            follows: components["schemas"]["FollowRelation"][];
            drafts: {
                [key: string]: Record<string, never>;
            };
            draftOwners: {
                [key: string]: string;
            };
        };
        ActionResult: {
            /** @constant */
            ok: true;
            data: unknown;
            stateVersion: number;
            meta: components["schemas"]["ActionMetadata"];
        } | {
            /** @constant */
            ok: false;
            error: string;
            message?: string;
            stateVersion: number;
            meta: components["schemas"]["ActionMetadata"];
            details?: unknown;
        };
        ActionMetadata: {
            sandboxId: string;
            actorId: string;
            stateVersion: number;
            operationId: string;
            commandId?: string;
            requestId?: string;
            idempotencyKey?: string;
            /** @enum {string} */
            mode: "preview" | "commit";
        };
        SandboxPreviewInput: {
            /** @example schemathesis */
            sandboxId?: string;
            /** @enum {string} */
            command: "purchase" | "listing.create" | "wallet.deposit" | "wallet.withdraw";
            payload: Record<string, never>;
            stateVersion?: number;
            expectedStateVersion?: number;
            operationId?: string;
            commandId?: string;
            requestId?: string;
            idempotencyKey?: string;
        } & (unknown & unknown & unknown);
        SandboxCommitInput: {
            /** @example schemathesis */
            sandboxId?: string;
            previewId: string;
            stateVersion?: number;
            expectedStateVersion?: number;
            operationId?: string;
            commandId?: string;
            requestId?: string;
            idempotencyKey: string;
        };
        ActionResultPreview: components["schemas"]["ActionResult"];
        SandboxHealth: {
            /** @constant */
            ok: true;
            ready: boolean;
            sandboxId: string;
            stateVersion: number;
            /** @enum {string} */
            storage: "memory" | "d1";
            capabilities: {
                [key: string]: boolean;
            };
        };
        SandboxSeedInput: {
            /** @example schemathesis */
            id?: string;
            /** @example schemathesis */
            sandboxId?: string;
            /**
             * @default catalog_default
             * @enum {string}
             */
            scenarioId: "catalog_default" | "purchase_happy_path" | "already_sold" | "multi_inventory" | "auction_outbid" | "listing_policy_blocked" | "zero_search_results" | "payment_timeout" | "delivery_delay";
            seed?: string;
            expectedStateVersion?: number;
        };
        SandboxOperationResponse: {
            /** @constant */
            ok: true;
            /** @enum {string} */
            operation: "reset" | "seed";
            sandboxId: string;
            scenarioId?: string;
            seed?: string;
            stateVersion: number;
            state: components["schemas"]["SandboxState"];
        };
        SandboxReplayInput: {
            /** @example schemathesis */
            id?: string;
            /** @example schemathesis */
            sandboxId?: string;
            /**
             * @default catalog_default
             * @enum {string}
             */
            scenarioId: "catalog_default" | "purchase_happy_path" | "already_sold" | "multi_inventory" | "auction_outbid" | "listing_policy_blocked" | "zero_search_results" | "payment_timeout" | "delivery_delay";
            seed?: string;
            baseState?: string;
            /** @description 保存済みSandboxを現在のreplay基準にする場合はtrue。seed/reset直後の状態へ続けて操作する場合に指定する。 */
            fromStored?: boolean;
            expectedStateVersion?: number;
            actions: {
                /** @enum {string} */
                command: "listItem" | "createListingDraft" | "updateListingDraft" | "deleteListingDraft" | "submitListing" | "startPurchase" | "confirmPurchase" | "purchaseItem" | "buyItem" | "placeBid" | "closeAuction" | "shipOrder" | "markDelivered" | "reviewOrder" | "cancelOrder" | "resolveCancellation" | "reviewListing" | "requestReturn" | "confirmReturnReceived" | "sendTransactionMessage" | "createSupportTicket" | "reportTransaction" | "updateListing" | "pauseListing" | "resumeListing" | "relistItem" | "updateProfile" | "getFollowList" | "getFollowSummary" | "followUser" | "unfollowUser" | "depositWallet" | "withdrawWallet" | "switchActor" | "loadScenario" | "resetScenario" | "advanceClock" | "injectFailure" | "importState";
                payload?: {
                    [key: string]: unknown;
                };
                idempotencyKey?: string;
            }[];
        };
        SandboxReplayResponse: {
            /** @constant */
            ok: true;
            /** @constant */
            operation: "replay";
            sandboxId: string;
            stateVersion: number;
            results: unknown[];
            trace: unknown[];
            state: components["schemas"]["SandboxState"];
        };
        ErrorResponse: {
            /** @constant */
            ok: false;
            error: string;
            details?: unknown;
        };
    };
    responses: {
        /** @description 入力が不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 認証が必要 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 権限不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description stateVersionまたはETagが競合 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description リソースが存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description D1など依存サービスが利用できない */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ItemId: string;
        Offset: number;
        Limit: number;
        IfMatchStateVersion: number;
    };
    requestBodies: never;
    headers: {
        /** @description リソースのバージョン */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSandboxState: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox状態 */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxState"];
                };
            };
            /** @description 変更なし */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    putSandboxState: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: {
                "If-Match-State-Version"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxState"];
            };
        };
        responses: {
            /** @description 保存済み状態 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        id: string;
                        stateVersion: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description 状態が8MiBを超えた */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    previewSandboxAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxPreviewInput"];
            };
        };
        responses: {
            /** @description preview結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResultPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description payloadが8MiBを超えた */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    commitSandboxPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxCommitInput"];
            };
        };
        responses: {
            /** @description commit結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    resetSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SandboxSeedInput"];
            };
        };
        responses: {
            /** @description リセット済みSandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxOperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description JSON bodyのContent-Typeが必要 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    seedSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxSeedInput"];
            };
        };
        responses: {
            /** @description seed済みSandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxOperationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description JSON bodyのContent-Typeが必要 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    replaySandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxReplayInput"];
            };
        };
        responses: {
            /** @description 再生後のSandbox */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxReplayResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            /** @description JSON bodyのContent-Typeが必要 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description command列の途中で失敗した */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
}
